os_username: dsantoro
os_tenant: "ict"
os_auth_url: "http://217.77.95.1:5000/v2.0"
os_region_name: "OS1Public"
os_ssh_key_name: "dsantoro_cn"
os_flavor: "m1.small"
os_image: "550a59ca-cb23-4ed4-9813-98d91a1783b2"
os_security_groups:
  - "allowall"
 #- some_other_group
os_floating_ip_pool: "vlab_external"
os_ssh_pub_key_path: "~/.ssh/id_rsa_cn"
os_instance_username: "ubuntu"

# Siris specific additions
os_openstack_compute_url: "http://217.77.95.1:8774/v2/e08dfba237344558be5135f9c93c5095"
os_networks: "97ca6ee7-abf5-4737-bae1-4654476ef690"