os_username: SIRIS_USERNAME
os_tenant: "SIRIS_TENANT"
os_auth_url: "http://SIRIS_API_IP:5000/v2.0"
os_region_name: "OS1Public"
os_ssh_key_name: "SIRIS_KEYNAME"
os_flavor: "m1.small"
os_image: "550a59ca-cb23-4ed4-9813-98d91a1783b2"
os_security_groups:
  - "allowall"
 #- some_other_group
os_floating_ip_pool: "SIRIS_NET_NAME"
os_ssh_pub_key_path: "PATH_TO_LOCAL_SSH_KEY"
os_instance_username: "ubuntu"

# Siris specific additions
os_openstack_compute_url: "SIRIS_COMPUTE_URL"
os_networks: "SIRIS_NET_UUID"